### ISSUE TITLE
first install fails

### ISSUE THREAD

**Issue by sebgoa** [nats-io/asyncio-nats#38]
I tried to install, first try fails, probably my fault, but it is strange

```
$ sudo pip install asyncio-nats-client
Password:
The directory '/Users/sebgoa/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/sebgoa/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting asyncio-nats-client
  Downloading asyncio-nats-client-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-5STZqO/asyncio-nats-client/setup.py", line 2, in <module>
        from nats.aio.client import __version__
      File "nats/__init__.py", line 10
        yield from nc.connect(**options)
                 ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-5STZqO/asyncio-nats-client/
```

**Comment by sebgoa** [comment]
ok, I think the readme should be a little clearer that this is python3.6:

```
sudo pip3.6 install asyncio-nats-client
The directory '/Users/sebgoa/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/sebgoa/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting asyncio-nats-client
  Downloading asyncio-nats-client-0.5.0.tar.gz
Installing collected packages: asyncio-nats-client
  Running setup.py install for asyncio-nats-client ... done
Successfully installed asyncio-nats-client-0.5.0
```
